name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: remove go
      run: sudo rm $(type -p go)
    - name: install go
      run: sudo apt update && sudo apt install golang-go -y
    - name: make
      run: make
