name: go test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.8'
    - name: quicksort
      run: GOPATH=${PWD} go test quicksort
    - name: strategy_pattern
      run: GOPATH=${PWD} go test strategy_pattern
    - name: observer_pattern
      run: GOPATH=${PWD} go test observer_pattern
